Laravel/SpotyFake/src/Entity/Disco.php
<?php

namespace App\Entity;

use App\Repository\DiscoRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: DiscoRepository::class)]
class Disco
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $titulo = null;

    #[ORM\Column(type: Types::DATE_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $fecha_lanzamiento = null;

    #[ORM\ManyToOne]
    #[ORM\JoinColumn(nullable: false)]
    private ?Cantante $cantante_id = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitulo(): ?string
    {
        return $this->titulo;
    }

    public function setTitulo(string $titulo): self
    {
        $this->titulo = $titulo;

        return $this;
    }

    public function getFechaLanzamiento(): ?\DateTimeInterface
    {
        return $this->fecha_lanzamiento;
    }

    public function setFechaLanzamiento(?\DateTimeInterface $fecha_lanzamiento): self
    {
        $this->fecha_lanzamiento = $fecha_lanzamiento;

        return $this;
    }

    public function getCantanteId(): ?Cantante
    {
        return $this->cantante_id;
    }

    public function setCantanteId(?Cantante $cantante_id): self
    {
        $this->cantante_id = $cantante_id;

        return $this;
    }
}

Laravel/SpotyFake/src/Form/DiscoType.php
<?php

namespace App\Form;

use App\Entity\Disco;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class DiscoType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('titulo')
            ->add('fecha_lanzamiento')
            ->add('cantante_id', null, array(
                'class' => 'App\Entity\Cantante',
                'choice_label' => 'nombre',
                'multiple' => false,
                'expanded' => false,
                'required' => true,
                'placeholder' => 'Seleccione un cantante'
            ))
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Disco::class,
        ]);
    }
}

Laravel/SpotyFake/src/Controller/DiscoController.php
<?php

namespace App\Controller;

use App\Entity\Disco;
use App\Form\Disco1Type;
use App\Repository\DiscoRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/disco')]
class DiscoController extends AbstractController
{
    #[Route('/', name: 'app_disco_index', methods: ['GET'])]
    public function index(DiscoRepository $discoRepository): Response
    {
        return $this->render('disco/index.html.twig', [
            'discos' => $discoRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_disco_new', methods: ['GET', 'POST'])]
    public function new(Request $request, DiscoRepository $discoRepository): Response
    {
        $disco = new Disco();
        $form = $this->createForm(Disco1Type::class, $disco);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $discoRepository->save($disco, true);

            return $this->redirectToRoute('app_disco_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('disco/new.html.twig', [
            'disco' => $disco,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_disco_show', methods: ['GET'])]
    public function show(Disco $disco): Response
    {
        return $this->render('disco/show.html.twig', [
            'disco' => $disco,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_disco_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Disco $disco, DiscoRepository $discoRepository): Response
    {
        $form = $this->createForm(Disco1Type::class, $disco);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $discoRepository->save($disco, true);

            return $this->redirectToRoute('app_disco_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('disco/edit.html.twig', [
            'disco' => $disco,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_disco_delete', methods: ['POST'])]
    public function delete(Request $request, Disco $disco, DiscoRepository $discoRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$disco->getId(), $request->request->get('_token'))) {
            $discoRepository->remove($disco, true);
        }

        return $this->redirectToRoute('app_disco_index', [], Response::HTTP_SEE_OTHER);
    }
}

Laravel/SpotyFake/templates/disco/_delete_form.html.twig
<form method="post" action="{{ path('app_disco_delete', {'id': disco.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ disco.id) }}">
    <button class="btn">Delete</button>
</form>

Laravel/SpotyFake/templates/disco/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

Laravel/SpotyFake/templates/disco/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Disco{% endblock %}

{% block body %}
    <h1>Edit Disco</h1>

    {{ include('disco/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_disco_index') }}">back to list</a>

    {{ include('disco/_delete_form.html.twig') }}
{% endblock %}

Laravel/SpotyFake/templates/disco/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Disco index{% endblock %}

{% block body %}
    <h1>Disco index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Titulo</th>
                <th>Fecha_lanzamiento</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for disco in discos %}
            <tr>
                <td>{{ disco.id }}</td>
                <td>{{ disco.titulo }}</td>
                <td>{{ disco.fechaLanzamiento ? disco.fechaLanzamiento|date('Y-m-d') : '' }}</td>
                <td>
                    <a href="{{ path('app_disco_show', {'id': disco.id}) }}">show</a>
                    <a href="{{ path('app_disco_edit', {'id': disco.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="4">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_disco_new') }}">Create new</a>
{% endblock %}

Laravel/SpotyFake/templates/disco/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Disco{% endblock %}

{% block body %}
    <h1>Create new Disco</h1>

    {{ include('disco/_form.html.twig') }}

    <a href="{{ path('app_disco_index') }}">back to list</a>
{% endblock %}

Laravel/SpotyFake/templates/disco/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Disco{% endblock %}

{% block body %}
    <h1>Disco</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ disco.id }}</td>
            </tr>
            <tr>
                <th>Titulo</th>
                <td>{{ disco.titulo }}</td>
            </tr>
            <tr>
                <th>Fecha_lanzamiento</th>
                <td>{{ disco.fechaLanzamiento ? disco.fechaLanzamiento|date('Y-m-d') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_disco_index') }}">back to list</a>

    <a href="{{ path('app_disco_edit', {'id': disco.id}) }}">edit</a>

    {{ include('disco/_delete_form.html.twig') }}
{% endblock %}