Laravel/SpotyFake/src/Entity/Cantante.php
<?php

namespace App\Entity;

use App\Repository\CantanteRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: CantanteRepository::class)]
class Cantante
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $nombre = null;

    #[ORM\Column(type: Types::DATE_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $fecha_nacimiento = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNombre(): ?string
    {
        return $this->nombre;
    }

    public function setNombre(string $nombre): self
    {
        $this->nombre = $nombre;

        return $this;
    }

    public function getFechaNacimiento(): ?\DateTimeInterface
    {
        return $this->fecha_nacimiento;
    }

    public function setFechaNacimiento(?\DateTimeInterface $fecha_nacimiento): self
    {
        $this->fecha_nacimiento = $fecha_nacimiento;

        return $this;
    }
}

Laravel/SpotyFake/src/Form/CantanteType.php
<?php

namespace App\Form;

use App\Entity\Cantante;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class CantanteType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('nombre')
            ->add('genero')
            ->add('fecha_nacimiento')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Cantante::class,
        ]);
    }
}

Laravel/SpotyFake/src/Controller/CantanteController.php
<?php

namespace App\Controller;

use App\Entity\Cantante;
use App\Form\Cantante1Type;
use App\Repository\CantanteRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/cantante')]
class CantanteController extends AbstractController
{
    #[Route('/', name: 'app_cantante_index', methods: ['GET'])]
    public function index(CantanteRepository $cantanteRepository): Response
    {
        return $this->render('cantante/index.html.twig', [
            'cantantes' => $cantanteRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_cantante_new', methods: ['GET', 'POST'])]
    public function new(Request $request, CantanteRepository $cantanteRepository): Response
    {
        $cantante = new Cantante();
        $form = $this->createForm(Cantante1Type::class, $cantante);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $cantanteRepository->save($cantante, true);

            return $this->redirectToRoute('app_cantante_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('cantante/new.html.twig', [
            'cantante' => $cantante,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_cantante_show', methods: ['GET'])]
    public function show(Cantante $cantante): Response
    {
        return $this->render('cantante/show.html.twig', [
            'cantante' => $cantante,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_cantante_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Cantante $cantante, CantanteRepository $cantanteRepository): Response
    {
        $form = $this->createForm(Cantante1Type::class, $cantante);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $cantanteRepository->save($cantante, true);

            return $this->redirectToRoute('app_cantante_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('cantante/edit.html.twig', [
            'cantante' => $cantante,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_cantante_delete', methods: ['POST'])]
    public function delete(Request $request, Cantante $cantante, CantanteRepository $cantanteRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$cantante->getId(), $request->request->get('_token'))) {
            $cantanteRepository->remove($cantante, true);
        }

        return $this->redirectToRoute('app_cantante_index', [], Response::HTTP_SEE_OTHER);
    }
}

Laravel/SpotyFake/templates/cantante/_delete_form.html.twig
<form method="post" action="{{ path('app_cantante_delete', {'id': cantante.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ cantante.id) }}">
    <button class="btn">Delete</button>
</form>

Laravel/SpotyFake/templates/cantante/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

Laravel/SpotyFake/templates/cantante/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Cantante{% endblock %}

{% block body %}
    <h1>Edit Cantante</h1>

    {{ include('cantante/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_cantante_index') }}">back to list</a>

    {{ include('cantante/_delete_form.html.twig') }}
{% endblock %}

Laravel/SpotyFake/templates/cantante/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Cantante index{% endblock %}

{% block body %}
    <h1>Cantante index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Nombre</th>
                <th>Fecha_nacimiento</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for cantante in cantantes %}
            <tr>
                <td>{{ cantante.id }}</td>
                <td>{{ cantante.nombre }}</td>
                <td>{{ cantante.fechaNacimiento ? cantante.fechaNacimiento|date('Y-m-d') : '' }}</td>
                <td>
                    <a href="{{ path('app_cantante_show', {'id': cantante.id}) }}">show</a>
                    <a href="{{ path('app_cantante_edit', {'id': cantante.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="4">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_cantante_new') }}">Create new</a>
{% endblock %}

Laravel/SpotyFake/templates/cantante/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Cantante{% endblock %}

{% block body %}
    <h1>Create new Cantante</h1>

    {{ include('cantante/_form.html.twig') }}

    <a href="{{ path('app_cantante_index') }}">back to list</a>
{% endblock %}

Laravel/SpotyFake/templates/cantante/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Cantante{% endblock %}

{% block body %}
    <h1>Cantante</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ cantante.id }}</td>
            </tr>
            <tr>
                <th>Nombre</th>
                <td>{{ cantante.nombre }}</td>
            </tr>
            <tr>
                <th>Fecha_nacimiento</th>
                <td>{{ cantante.fechaNacimiento ? cantante.fechaNacimiento|date('Y-m-d') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_cantante_index') }}">back to list</a>

    <a href="{{ path('app_cantante_edit', {'id': cantante.id}) }}">edit</a>

    {{ include('cantante/_delete_form.html.twig') }}
{% endblock %}